### ISSUE TITLE
逻辑优化：客户端部署

### ISSUE THREAD

**Issue by septs** [likexian/stathub-go#1]
```
on 32 bits node
$ wget http://IP:15944/static/client_x86 -O client
on 64 bits node
$ wget http://IP:15944/static/client_x86_64 -O client
```

可优化为：`wget http://IP:15944/static/client_$(uname -m) -O stathub_client && chmod +x stathub_client`

**Comment by likexian** [comment]
感谢Sept，我下一版本改过来。

**Comment by septs** [comment]
另外希望能提供预配置client.json下载
期望例示：`wget http://IP:15944/client.json?name=test1 -O client.json`

**Comment by likexian** [comment]
嗯，这个建议不错，当时没做是因为hostname处理起来比较麻烦。

**Comment by septs** [comment]
仔细想了想想 做成sh也许最方便

> 期望例示：`wget -O - http://IP:15944/client?profile=centos5 | sh`
> 期望例示：`wget -O - http://IP:15944/client?profile=centos5&name=test1 | sh`

对运维的会轻松很多
sh下获取hostname, 内核架构(uname -m) 等信息比较方便
profile如果能提供支持最好 比如在server端放一个profile比如针对CentOS5的profile脚本
那么部署在CentOS5就不需要太操心执行

> 期望例示：`wget -O - http://IP:15944/client?profile=centos5&name=test1 | sh`

即可

**Comment by likexian** [comment]
嗯，客户端安装的确有想过用sh做。

**Comment by likexian** [comment]
最新发布的版本已按第1个贴的建议进行修改。
接下来我还会继续优化这里，以让部署更加方便。
谢谢 @Septembers 。

**Comment by likexian** [comment]
最新发布的版本再次优化了客户端安装，现在执行一行sh就可以完成了，欢迎使用。

**Comment by septs** [comment]
脚本存在三个问题
1. 没做读写权限检查
2. 没做wget可用性检查
3. 没做crond可用性检查
**在最小化安装的VPS上wget, crond都是默认没有安装的。。。。。**

**Comment by likexian** [comment]
这种情况下出错了会有相应的提示的，可以根据提示来解决，我再加一个提示也是一样的。

**Comment by septs** [comment]
但是遇到傻逼用户 不加个提示就。。。。。。

**Comment by likexian** [comment]
嗯，说的也是，我后续再看看这里。

**Comment by septs** [comment]
```
$ curl --insecure https://{{.server}}/node?key={{.key}} | sh
```

key不需要把一个server只有一个key
不更需要name吗？ [see](https://github.com/likexian/stathub-go/blob/master/server/template/node.html#L16)

**Comment by likexian** [comment]
key肯定是要的，要不别人都可以下你的配置了。
name没有就用hostname，是可选的。不过你也可以通过client.json自定义name。

**Comment by septs** [comment]
那么希望增加**可选的name**，分发会更简单

```
$ curl --insecure https://{{.server}}/node?key={{.key}}&name=node1 | sh
```

**Comment by likexian** [comment]
问题是这个name不好输入啊。
