### ISSUE TITLE
希望引入 kardianos/service 注册成系统服务

### ISSUE THREAD

**Issue by septs** [likexian/stathub-go#11]
see https://stackoverflow.com/questions/24357887
see https://github.com/kardianos/service

其实我是想在Windows下使用Client

**Comment by likexian** [comment]
谢谢 @Septembers 。
近来我一直在看daemon的相关资料，这里是得更好地解决掉。
然后默认 client 目前不支持 windows，近期没有时间支持，后续再根据情况看看。

**Comment by likexian** [comment]
目前这个项目是不支持跑在 windows 或 osx 下的，特别是客户端由于系统原因是完全不支持的，短时间内也没有支持的计划。然而你可以通过编写一个自己的脚本来向服务器提交数据，理论上在任何系统下都可以实现。而对于daemon方案，上面的两个连接并不适用，后续我会继续跟进daemon的实现。所以这个单暂时先关掉了，敬请继续关注。
