### ISSUE TITLE
系统提示我升级~问下怎么升级？

### ISSUE THREAD

**Issue by ShenXuGongZi** [likexian/stathub-go#13]
客户端也要再来一遍吗？

**Comment by likexian** [comment]
升级跟全新安装是一样的，只需要将文件覆盖，然后重启下进程就好了。
您可以直接在服务端执行以下命令升级服务端：
curl --insecure https://raw.githubusercontent.com/likexian/stathub-go/master/setup.sh | sh

客户端现在的确得挨个重新下载新的client来升级，也是跟新安装一下。
在服务端 http://服务端ip:15944/help 可以看到安装命令，也执行一下。

目前已经开始计划做升级完服务端自动升级客户端了，这个功用有了以后就会省事很多很多了。

**Comment by ShenXuGongZi** [comment]
我想问下这次 升级的内容 因为我看遍了官方文档 也没有找到这次到底升级了什么内容 =，= 烦请您说下 谢谢啦!

**Comment by likexian** [comment]
各个版本的变更内容可以看：https://github.com/likexian/stathub-go/blob/master/CHANGS-ZH.md

**Comment by ShenXuGongZi** [comment]
0.10.2 Beta 版本的变更 2015-05-28

特性：一行命令安装客户端
特性：一行命令安装服务端

=，= 没有看懂 以前也是一行安装啊!

**Comment by likexian** [comment]
以前的安装过程比较复杂，需要手动执行一堆命令，现在可以直接执行
curl --insecure https://raw.githubusercontent.com/likexian/stathub-go/master/setup.sh | sh
完成整个安装过程。

**Comment by ShenXuGongZi** [comment]
好吧 谢谢 我想这次不用升级了。。下个版本在升级好了~~ 辛苦了！

**Comment by likexian** [comment]
嗯，没问题的，近两个版本都不会有大功能上的更新，主要是优化，所以能正常用的，都可以跳过最近这个版本以及下一个版本。
