### ISSUE TITLE
请求下个版本 可以自定义服务器Name

### ISSUE THREAD

**Issue by ShenXuGongZi** [likexian/stathub-go#14]
现在是从子机器直接提取Name 并不能自定义，请求下个版本加入自定义，以及api 调用 可以把一些不重要的数据，比如流量 放开查看。。这样就不需要每次输入密码查看了。

**Comment by likexian** [comment]
要自定义Name，修改client.json中的name的内容就可以了。

**Comment by likexian** [comment]
放开某些数据这个没有计划，不过有计划做API，以后可以通过API实现这个需求。
