### ISSUE TITLE
你好大大，请教下为何我的安装后

### ISSUE THREAD

**Issue by kankankankankankan** [likexian/stathub-go#16]
![z33fhe j_u g 1p og 2 4](https://cloud.githubusercontent.com/assets/11487346/11449977/8004ee18-95c5-11e5-8cec-679e4ede8dae.png)
本机不显示实时流量等信息，其他的客户端倒是没问题
不知道怎样解决 多谢

**Comment by likexian** [comment]
这条记录背景是红色的，说明数据已经停止上报了，你看看crontab -l中还有没有sathub的命令。

**Comment by kankankankankankan** [comment]
好的，收到 多谢了

**Comment by likexian** [comment]
解决了吗？

**Comment by kankankankankankan** [comment]
好了  多谢

**Comment by likexian** [comment]
好，有问题再找我
