### ISSUE TITLE
Installation script issue.

### ISSUE THREAD

**Issue by orasul** [likexian/stathub-go#17]
Can't install master using proposed installation script:

wget --no-check-certificate -O - https://raw.githubusercontent.com/likexian/stathub-go/master/setup.sh | sh
--2016-02-26 15:12:13--  https://raw.githubusercontent.com/likexian/stathub-go/master/setup.sh
....
Length: 2124 (2.1K) [text/plain]
Saving to: “STDOUT”

100%[===============================================================================================================================>] 2,124       --.-K/s   in 0s      

2016-02-26 15:12:14 (604 MB/s) - written to stdout [2124/2124]

sh: line 8: syntax error near unexpected token `else'
sh: line 8:`else'

GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)

**Comment by likexian** [comment]
Hello, Thank you for your feedback, I will take a look at it soon.

**Comment by zfjoy520** [comment]
`sh: line 8: syntax error near unexpected token`else'
sh: line 8: `else'`
同上，安装不起呢，样子看起来不错，果断star，果断fork

**Comment by gensmusic** [comment]
same error here

**Comment by likexian** [comment]
This issue will be fixed in next version, some days later.

**Comment by gensmusic** [comment]
it's an easy fix and nothing about version since you are using master branch.

**Comment by likexian** [comment]
Issue fixed, thanks to @gensmusic 
Will @orasul @zfjoy520 try again?
