### ISSUE TITLE
安全问题：HTTPS支持

### ISSUE THREAD

**Issue by septs** [likexian/stathub-go#2]
希望能使用自签发证书

**Comment by likexian** [comment]
多谢Sept，我会考虑的，也欢迎pr。

**Comment by septs** [comment]
golang还在学习 目前没能力

**Comment by likexian** [comment]
嗯，谢谢您的支持和建议。

**Comment by likexian** [comment]
最新发布的版本已经支持 https，默认是自签名的，您可以使用您的证书替换掉cert下的文件以使用有效的证书。
十分感谢 @Septembers 和 @Bluek404 。
