### ISSUE TITLE
errors after setup.sh

### ISSUE THREAD

**Issue by gensmusic** [likexian/stathub-go#20]
> server_x86_64.tar.gz                                100%> [===================================================================================================================>]   1.87M  86.4KB/s   in 23s    
> 
> 2016-03-18 15:16:35 (81.5 KB/s) - ‘server_x86_64.tar.gz’ saved [1955924/1955924]
> ---
> 
> | Server install sucessful, Please start it using  |
> | ./service {start|stop|restart}                   |
> | Now it will automatic start                      |
> |                                                  |
> | Feedback: https://github.com/likexian/stathub-go |
> | Thank you for your using, By Li Kexian           |
> ## | StatHub, Apache License, Version 2.0             |
> 
> starting
> ## ok
> 
> | Please open the below URL on your PC browser:    |
> | https://this-server-ip:15944                     |
> | Default password: likexian                       |
> |                                                  |
> | Feedback: https://github.com/likexian/stathub-go |
> | Thank you for your using, By Li Kexian           |
> ## | StatHub, Apache License, Version 2.0             |
> 
> wget is a tracked alias for /usr/bin/wget
> --2016-03-18 15:16:36--  https://127.0.0.1:15944/node?key=4d09165f3ad77f160372e367ece6baef
> Connecting to 127.0.0.1:15944... failed: Connection refused.

I can't connect to https://127.0.0.1:15944 with chrome or firefox.
Also there is an error in the log above when i run `curl --insecure https://raw.githubusercontent.com/likexian/stathub-go/master/setup.sh | sh`

I check the /var/stathub/data and the log file is empty.
My OS is ubuntu 15.04 and 15.10(tried with two machines with same errors)

**Comment by likexian** [comment]
It seems that the server didn't start.
Will you please run:
cd /var/stathub/
./server
ps aux|grep server

**Comment by gensmusic** [comment]
it is started. I can see it running via `ps aux| grep server`

**Comment by likexian** [comment]
if started, it will listen on 15944, but you got a "Connection refused".

Do you have iptables stop access to 15944?

run follow to check listen port:
netstat -lntp|grep 15944

**Comment by likexian** [comment]
If fail again, please reopen the issue.
