### ISSUE TITLE
click password again and faile

### ISSUE THREAD

**Issue by ljh49670** [likexian/stathub-go#21]
我使用密码登录进去之后 ，再点击右上角的password，进入登录界面，这时输入密码likexian就不能登录。
console errror是 Failed to parse SourceMap: https://IP:15944/static/bootstrap.css.map

**Comment by likexian** [comment]
登录进去之后，再点击右上角的 password，此时进入的是修改密码界面，不是登录。输入的将会是新密码。

**Comment by ljh49670** [comment]
done.
我觉得Password,应该改成change password.你觉得呢

**Comment by likexian** [comment]
如果您还有其它问题，随时提交issue，谢谢使用。
