### ISSUE TITLE
nginx反代感觉有点问题啊

### ISSUE THREAD

**Issue by ruiruige** [likexian/stathub-go#24]
location /stathub/ {
          proxy_pass https://127.0.0.1:15944/;
           proxy_set_header X-Real-IP $remote_addr;  # 
     }

我把它写在配置文件里  不管 proxy_pass 后面的地址 是否加/  ，都会跳转到 localhost/login
而本应该跳转到 localhost/stathub/login
感觉像是写死了跳转

**Comment by likexian** [comment]
这里是有点问题，待我找个时间修一下。

**Comment by likexian** [comment]
很抱歉，经过多重考虑，还是决定不支持子目录方式来部署到nginx上。
建议使用一个单独的域名来部署，在nginx上用以下配置：
location / {
proxy_pass https://127.0.0.1:15944/;
proxy_set_header X-Real-IP $remote_addr; 
}
