### ISSUE TITLE
在几台机子上Client都无法正常启动

### ISSUE THREAD

**Issue by bestony** [likexian/stathub-go#26]
执行 `ps -ef | grep client`
都找不到启动的client的连接
即使手动到 /var/stathub/下执行client都无法保证启动。

**Comment by bestony** [comment]
Centos 7  DigitalOcean SFO2

**Comment by likexian** [comment]
client不是长驻进程，是通过crontab每分钟执行一次的，你看下 crontab -l 有没有对应的记录
