### ISSUE TITLE
磁盘空间占用数字显示错误

### ISSUE THREAD

**Issue by xdstack** [likexian/stathub-go#28]
多除了个100。

另外带宽那列代表什么呢。

![image](https://user-images.githubusercontent.com/1461065/29739155-c2f2c8b8-8a69-11e7-9aba-9cf8a8495222.png)

**Comment by likexian** [comment]
磁盘空间占用 数字没问题啊
带宽那列现在的说法有问题，事实上是月已用流量，下次我会改过来。

**Comment by likexian** [comment]
@xdstack 感谢你的反馈，磁盘空间占用显示的确存在问题，现已经修复了，你可以再试试最新版，有问题随时联系。
