### ISSUE TITLE
能否在列表里面添加一个主机标识呢

### ISSUE THREAD

**Issue by sinnerliu** [likexian/stathub-go#29]
![image](https://user-images.githubusercontent.com/14275089/35090819-cfa5769a-fc75-11e7-8829-8edff48aef2c.png)
能否在列表里面添加一个主机标识呢，在启动client的时候，后面添加一个参数，或者在安装client的时候在client.json中添加一个参数来说明这个主机是干什么的呢。
例如：
![image](https://user-images.githubusercontent.com/14275089/35090976-5288bb6c-fc76-11e7-92fb-a397611b0771.png)

**Comment by likexian** [comment]
你看下 client.json 这个文件，里面有个字段是 name，设置你想要的名称就可以了。

**Comment by sinnerliu** [comment]
嗯嗯，刚刚试了下， client.json 里面配置了name，前台展现在之前主机名那儿了，多谢指点

**Comment by likexian** [comment]
感谢支持
