### ISSUE TITLE
很不错的项目,使用了一段时间.

### ISSUE THREAD

**Issue by Senrt** [likexian/stathub-go#30]
您在V2EX发帖的时候就有V友询问有没有 Windows client 的考虑.
https://www.v2ex.com/t/184177#r_1982552

请问有这个 Windows client 打算吗,还是说你把项目忘了哈哈哈.

**Comment by likexian** [comment]
项目还在继续，不过由于近年工作繁忙所以进展缓慢，也一直没有出新版本。Windows client目前还没有考虑。
