### ISSUE TITLE
问一下安装客户端的时候，已经按提示安装了，但是数据没有显示在页面上

### ISSUE THREAD

**Issue by baosi1234** [likexian/stathub-go#31]
页面没有显示
![image](https://user-images.githubusercontent.com/14026068/39953897-b125096c-55e7-11e8-99b1-9dace5b44fec.png)
客户端执行了
![image](https://user-images.githubusercontent.com/14026068/39953906-c65b06f6-55e7-11e8-8349-b47cb5c77484.png)
也没有客户端client.log日志生成是怎么回事

**Comment by likexian** [comment]
你再单独执行一下 ./client 看看有没有数据展示；如果还是没有，试试 curl -v https://10.78.200.1:15944 看看。

**Comment by likexian** [comment]
欢迎再试下新版本，如果有问题再反馈。
