### ISSUE TITLE
磁盘空间占用显示不对

### ISSUE THREAD

**Issue by baosi1234** [likexian/stathub-go#32]
![image](https://user-images.githubusercontent.com/14026068/39979503-709e7124-5779-11e8-8358-024ea4540599.png)
应该显示成21%
![image](https://user-images.githubusercontent.com/14026068/39979551-baacfe70-5779-11e8-8066-8f7dd9e01cca.png)
应该显示成94.8%

**Comment by likexian** [comment]
图1 是全部磁盘的空间加在一起算的
图2 是说 / 分区这一个分区占用出现警告了
你可以重新确认下是否正确

**Comment by baosi1234** [comment]
可以加一下你的QQ跟你联系一下么

**Comment by likexian** [comment]
很少上QQ，有问题你可以直接说

**Comment by baosi1234** [comment]
我把客户端部署在服务器上的时候经常出现很多个client的进程，占用CPU资源的情况

**Comment by likexian** [comment]
目前的版本是一分钟启动一次client单独去执行一次收集和上报，如果上报的网络不好会一直等待与重试，造成多个client一起出现的情况，不过资源占用应该是很少的。
这个后续的版本会有所优化。

**Comment by baosi1234** [comment]
还有版本升级的问题，以后版本升级了，客户端和服务端都要更新么

**Comment by likexian** [comment]
现在是的，都需要更新。
下一个版本会支持只升级服务端就可以了。

**Comment by likexian** [comment]
@baosi1234 感谢你的反馈，你提到的磁盘空间占用显示不对的问题已经修复了，你可以再试试最新版，有问题随时联系。
