### ISSUE TITLE
使用 ./service stop 进程并没有被杀死

### ISSUE THREAD

**Issue by dryyun** [likexian/stathub-go#34]
使用了 ./service stop 进程并没有被杀死，pid 文件倒是被删掉了   
看了一下 service  源码   
```
stop() {
    echo "stopping"
    if [ -f $PID ]; then
        kill `cat $PID`
        rm -rf $PID
        echo "ok"
    fi
}
```

建议使用 kill -9 强制杀死   
`kill ` 会发送 `SIGTERM` 信号给程序，然后看程序怎么做了   
`kill -9 ` 会发送 `SIGKILL` 信号给程序，强杀

**Comment by likexian** [comment]
谢谢你的建议。

**Comment by likexian** [comment]
谢谢 @dryyun ，已暂时使用 -9 来 kill 进程，后面可能这里会继续有一些调整，有问题欢迎反馈。
