### ISSUE TITLE
不能监控服务端所在的服务器？

### ISSUE THREAD

**Issue by zxq1002** [likexian/stathub-go#6]
添加了服务端所在vps位节点但是没展示数据

**Comment by likexian** [comment]
服务端你运行了client吗？

**Comment by likexian** [comment]
服务端也需要跟客户端一样，将client跑起来才会有数据。建议按帮助里面的指引进行添加。
如果加了还是没有数据，可以看看 client.log 里面有没有出错日志。

**Comment by likexian** [comment]
在之前的两个版本中存在一个bug，如果服务器没有swap将收集不到数据。
最新发布的版本修复了这个问题，欢迎再试，没有数据的问题应该已经解决掉了，谢谢反馈。
