### ISSUE TITLE
net I/O不显示?

### ISSUE THREAD

**Issue by renjie45** [likexian/stathub-go#7]
![qq 20150420114059](https://cloud.githubusercontent.com/assets/9068568/7223330/25cf7a2a-e752-11e4-99f5-48606060a93d.png)
net i/o不显示怎么回事?

**Comment by likexian** [comment]
这个不是不显示，是当前没有网络请求，流量为0。

**Comment by renjie45** [comment]
第一个VPS只是用来做的SS服务,我看youtube的时候都没有流量显示?

**Comment by likexian** [comment]
你在服务器上wget一个大文件再看看有没流量？

**Comment by renjie45** [comment]
![qq](https://cloud.githubusercontent.com/assets/9068568/7223477/c772e68a-e754-11e4-8503-24f96c28be95.png)
是真的不显示,你看正在下载有流量也有在写盘.就是没有数据显示.

**Comment by likexian** [comment]
cat /proc/net/dev 看看

**Comment by renjie45** [comment]
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo: 5958145616 15261953    0    0    0     0          0         0 5958145616 15261953    0    0    0     0       0          0
venet0: 6952205300 15678264    0    0    0     0          0         0 13306501867 30593243    0  155    0     0       0          0

**Comment by likexian** [comment]
上面文件的内容没有问题，理论上是会有数据显示的。
数据会有一定时间的延时，它是定期更新的，你连续wget一分钟，一分钟后再刷新一下看看?

**Comment by renjie45** [comment]
好,我试下.

**Comment by renjie45** [comment]
还是没有显示,不知道怎么回事.

**Comment by likexian** [comment]
这。。。

**Comment by likexian** [comment]
这。。。
也没个日志啥的，不好定位啊。。。

**Comment by renjie45** [comment]
那等你把日志功能做出来再找找原因,?客户端和服务端只用了15944端口吧

**Comment by likexian** [comment]
服务端会监控15944端口，客户端会连接服务器的这个端口。

**Comment by renjie45** [comment]
那先不管了,我又不会编程,linux就会一点点.没法帮你找原因.

**Comment by likexian** [comment]
方便加个qq远程我看看吗？

**Comment by renjie45** [comment]
7832805

**Comment by likexian** [comment]
已加qq查看，初步判断是精度损失，我尽快解决。
十分感谢 @renjie45 的大力支持和帮忙！

**Comment by likexian** [comment]
之前没有数据显示应该是因为单位时间内流量过小，最新发布的版本优化了这一点。
@renjie45 可以试试最新的版本，看看这个问题还存不存在。

**Comment by renjie45** [comment]
终于更新了,我测试下.

**Comment by likexian** [comment]
欢迎 @renjie45 第一个测试，下载新的文件替换掉原来的，然后重启服务就可以用起来了。

**Comment by likexian** [comment]
这个版本再次优化了流量的精度，你可以再试试流量没有显示的问题有没有得到解决。

**Comment by renjie45** [comment]
好的,我空了试下.
