### ISSUE TITLE
Body invalid

### ISSUE THREAD

**Issue by vijaygadde** [likexian/stathub-go#9]
After setting-up client getting Body invalid

**Comment by likexian** [comment]
Body invalid means that the client report invalid json data to server.
Usually because the client collect unexpected data.
Which system is this client installed?

**Comment by vijaygadde** [comment]
Ubuntu 14

**Comment by likexian** [comment]
Thank you for your so quickly reply. Ubuntu is supported.
It seems that the log is not help for find out the problem.

**Comment by vijaygadde** [comment]
Sure

when i run ./client we are getting Body Invalid

**Comment by likexian** [comment]
Thank you!
Is this client 32 or 64 Bits?

**Comment by vijaygadde** [comment]
64bit, i just tried in CentOS 64 but, same error.

**Comment by likexian** [comment]
Will you try this client?
[URL expired]

**Comment by vijaygadde** [comment]
-bash: ./client: cannot execute binary file

Version:- Ubuntu 12.04.5 x32

**Comment by vijaygadde** [comment]
Body: -->  <--
Body invalid

Version:- Ubuntu 14.04 x64

**Comment by likexian** [comment]
The client collect empty stat, I will test it again on Ubuntu.
Thank you very much, @vijaygadde , I will release next version which you may try again.

**Comment by likexian** [comment]
I have find out why.
If the system have no SWAP, the client fail.
I will release the new version shortly, may you try again after that?

**Comment by vijaygadde** [comment]
yes the server don't have any swap for now. however i will swap on and try,

yes please let me know when the new version released.

**Comment by likexian** [comment]
thank you very much, @vijaygadde .

**Comment by vijaygadde** [comment]
after adding swap, it works.

**Comment by likexian** [comment]
yes, and the next version will work when swap is off.

**Comment by likexian** [comment]
Hello, the new version has released just now.
This version will work when swap is off, and add monthly bandwidth usage data.
